# Story Dossier Input
# Fill this out to generate your story dossier

# Basic Story Setup
title: "Untitled Urban Fantasy Romance"
genre: "fantasy romance"
subgenre: "urban fantasy romance"  # e.g., epic, urban, cozy, dark, etc.
heat_level: "explicit"  # sweet, steamy, explicit
target_audience: "adult"  # YA, NA, adult

# Structure
chapter_count: 28
target_word_count: 80000

# Blueprint Selection
# Choose which blueprint structure to use for the deep phase
# Available blueprints: epic-fantasy-romance, [add others as you create them]
blueprint: "urban-fantasy-romance"

# Romance Tropes (list all that apply)
tropes:
  - "enemies to lovers"
  - "Forbidden love"

# Additional Story Elements
magic_system_preference: "soft magic"
setting_preference: "contemporary with magic"  
tone: "action, adventure, fun with serious moments, witty banter" 

# Genre Research & Inspiration
# Paste your research, comp title notes, trope analysis, anything that informs this story
## Urban Fantasy Romance: Trending Tropes, Archetypes, Conflicts & Worldbuilding

### Dominant Tropes

**Enemies to Lovers** remains the heavyweight champion in urban fantasy romance. This trope works particularly well when characters have conflicting magical allegiances, opposing species loyalties, or philosophical divides about how to handle supernatural threats. The slow burn tension complements the genre's action-packed exterior.[1][2]

**Morally Gray Love Interests** are increasingly popular. Rather than true villains, readers crave characters who operate by their own moral compass—those willing to bend or break rules for justified reasons, carry traumatic pasts that shape their ethics, or navigate complex political/supernatural systems where "right" and "wrong" are ambiguous. These characters often start antagonistic or conflicted before revealing their depths.[2][3][4][1]

**Hidden Magical Societies and Forbidden Love** remain core tropes. The appeal lies in discovering a secret world existing parallel to mundane reality, often with established hierarchies, politics, and cultural tensions that make love across factions forbidden or dangerous.[5][2]

**Forced Proximity & Slow Burn** continue trending, allowing romantic tension to build naturally alongside external supernatural conflicts.[2]

### Character Archetypes

**The Reluctant Hero(ine)** dominates urban fantasy romance—protagonists who discover latent magical powers, are thrust into hidden supernatural politics, or must navigate dual identities (ordinary by day, magical by night). These characters often start as "everyperson" outsiders gaining insider knowledge.[6][1]

**The Dark Brooding Love Interest** persists strongly, particularly in morally gray variations. Think: mysterious, powerful characters carrying emotional wounds or dark secrets. They're often positions of authority or perceived danger but reveal unexpected depth and protective tendencies.[3][4][1]

**The Mundane Best Friend/Sidekick** who remains unaware of the magical world, or conversely, the "normie" best friend who unexpectedly steps into larger roles and becomes a grounding presence. These characters provide comic relief and perspective as anchors to the ordinary world.[7]

**Diverse Protagonists with Agency** are increasingly standard. Urban fantasy is shifting toward authors actively writing protagonists of various cultural backgrounds, identities, and body types who don't fit conventional "chosen one" molds.[8][6]

### Conflict Types

**Supernatural Crime-Solving and Investigation** remains popular. Murder mysteries, paranormal crimes, or supernatural threats requiring detective work combine mystery elements with romance.[9][10][11]

**Political Intrigue Within Hidden Supernatural Communities** creates ongoing tension—factions competing for power, centuries-old feuds, territorial disputes between different paranormal species. This works exceptionally well for serialized storytelling since political conflicts naturally escalate across books.[12][11][9][5]

**Change vs. Stagnation Themes**. Is magic disrupting a stagnant technological world, or is rapid change threatening established supernatural hierarchies? These ideological conflicts create compelling external pressures that force character growth.[9]

**Survival Against External Threats** (demonic invasions, interdimensional breaches, awakening ancient evils) force protagonists and love interests into alliance and vulnerability.[11][12]

**Secrets and Revelation Dynamics** where keeping the magical world hidden from mundane society creates constant tension—what happens if the secret gets out?[5]

### Worldbuilding Approaches

**Hidden/Parallel Supernatural Worlds** remain dominant. Magic exists secretly alongside modern cities—vampires in back alleys, fae in nightclubs, witches managing curses in downtown apartments. The juxtaposition of the magical and mundane is central to the appeal.[13][6][11][2][5]

**Organizational Power Structures** feature heavily—covens, guilds, hunter organizations, paranormal police forces, or magical courts maintaining order and enforcing supernatural laws. Since urban fantasy mirrors modern organizational structures, these create natural conflict and hierarchy.[12][9]

**Neo-Mythology**: Creating entirely new magical systems rather than relying solely on traditional lore. This allows unique worldbuilding but requires more authorial investment in establishing internal consistency.[9]

**Open Magic Worlds** (emerging trend): Some recent urban fantasy imagines worlds where magic has "awakened" and is no longer hidden, creating reimagined versions of technology and society where magic and science coexist. This is less common than hidden worlds but offers fresh territory for indie authors.[13][9]

**Diverse Mythological Fusion**: Authors increasingly blend diverse cultural mythologies, folklore, and magical traditions rather than relying solely on European paranormal creatures. This creates richer, more globally representative worldbuilding.[8]

### Current Reader Preferences (2025)

- **Established relationships receiving attention**: Readers explicitly want more stories featuring protagonists already married, engaged, or in committed partnerships rather than endless "meet and fall in love" arcs.[14]
- **Less miscommunication as plot device**: Reader fatigue with conflicts created solely by characters failing to communicate with each other.[14]
- **High spice content dominance**: Urban fantasy romance skews toward explicit sexual content, though low-spice options are emerging as a counter-trend.[15]
- **Cozy elements creeping in**: Urban fantasy is beginning to blend with cozy romance aesthetics—lower stakes, comfort elements—while maintaining paranormal worldbuilding.[15]
- **Diverse representation**: Ongoing demand for protagonists and supporting casts reflecting real-world diversity in race, sexuality, disability, body type, and age.[6][8]

Given your background with interconnected standalones featuring different couples, urban fantasy romance's natural fit for serialized storytelling with recurring secondary characters and expanding political conflicts could work exceptionally well for your series structure.
